version: "3"
services:
  janusgraph:
    image: janusgraph/janusgraph:0.6.1-90f2bbe
    ports:
      - "8182:8182"
    volumes:
      - ./configuration/janusgraph:/etc/opt/janusgraph/:ro
      - ./configuration/conf:/opt/janusgraph/conf/:ro
    container_name: "janusgraph"

  flask-app:
    build: ./app/
    command: sh -c "python3 -u /app/app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    container_name: "flask-app"

  gremlin-visualizer:
    image: prabushitha/gremlin-visualizer
    ports:
      - "3000:3000"
      - "3001:3001"
    container_name: "gremlin-visualizer"
  
  cassandra_p1:
    image: cassandra:3.11
    environment:
      - CASSANDRA_START_RPC=true
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M
    ports:
      - "9160"
      - "9042"
      - "7199"
      - "7001"
      - "7000"
    container_name: "cassandra_p1"

  cassandra_p2:
    image: cassandra:3.11
    ports:
      - "9160"
      - "9042"
      - "7199"
      - "7001"
      - "7000"
    environment:
      - CASSANDRA_START_RPC=true
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M
    container_name: "cassandra_p2"

  cassandra_r1:
    image: cassandra:3.11
    environment:
      - CASSANDRA_SEEDS=cassandra_p1
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=256M
    container_name: "cassandra_r1"


