version: "3"
services:
  janusgraph:
    image: docker.io/janusgraph/janusgraph
    ports:
      - "8182:8182"
    container_name: "janusgraph"

  flask-app:
    build: ./app/
    command: sh -c "python3 -u /app/app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    container_name: "flask-app"

  gremlin-visualizer:
    image: prabushitha/gremlin-visualizer
    ports:
      - "3000:3000"
      - "3001:3001"
    container_name: "gremlin-visualizer"